export type Episode = {
  id: string
  title: string
  date: string
  edition: 'morning' | 'evening'
  duration: string
  audioUrl: string
  description: string
  articleSlugs: string[]
}

// Auto-generated by update-podcast-data.py — do not edit manually
export const episodes: Episode[] = [
  {
    id: "2026-03-15-evening",
    title: "HackWire Daily Evening Brief — March 15, 2026",
    date: "2026-03-15",
    edition: "evening",
    duration: "5:00",
    audioUrl: "/podcast/episodes/hackwire-daily-2026-03-15-evening.mp3",
    description: "Top cybersecurity stories from March 15, 2026.",
    articleSlugs: []
  },
  {
    id: "2026-03-15-morning",
    title: "HackWire Daily Morning Brief — March 15, 2026",
    date: "2026-03-15",
    edition: "morning",
    duration: "5:00",
    audioUrl: "/podcast/episodes/hackwire-daily-2026-03-15-morning.mp3",
    description: "Top cybersecurity stories from March 15, 2026.",
    articleSlugs: []
  },
  {
    id: "2026-03-14-evening",
    title: "HackWire Daily Evening Brief — March 14, 2026",
    date: "2026-03-14",
    edition: "evening",
    duration: "5:00",
    audioUrl: "/podcast/episodes/hackwire-daily-2026-03-14-evening.mp3",
    description: "Top cybersecurity stories from March 14, 2026.",
    articleSlugs: []
  },
  {
    id: "2026-03-14-morning",
    title: "HackWire Daily Morning Brief — March 14, 2026",
    date: "2026-03-14",
    edition: "morning",
    duration: "5:00",
    audioUrl: "/podcast/episodes/hackwire-daily-2026-03-14-morning.mp3",
    description: "Top cybersecurity stories from March 14, 2026.",
    articleSlugs: []
  },
  {
    id: "2026-03-13-evening",
    title: "HackWire Daily Evening Brief — March 13, 2026",
    date: "2026-03-13",
    edition: "evening",
    duration: "5:00",
    audioUrl: "/podcast/episodes/hackwire-daily-2026-03-13-evening.mp3",
    description: "Top cybersecurity stories from March 13, 2026.",
    articleSlugs: []
  },
  {
    id: "2026-03-13-morning",
    title: "HackWire Daily Morning Brief — March 13, 2026",
    date: "2026-03-13",
    edition: "morning",
    duration: "5:00",
    audioUrl: "/podcast/episodes/hackwire-daily-2026-03-13-morning.mp3",
    description: "Top cybersecurity stories from March 13, 2026.",
    articleSlugs: []
  },
  {
    id: "2026-03-12-evening",
    title: "HackWire Daily Evening Brief — March 12, 2026",
    date: "2026-03-12",
    edition: "evening",
    duration: "5:00",
    audioUrl: "/podcast/episodes/hackwire-daily-2026-03-12-evening.mp3",
    description: "Top cybersecurity stories from March 12, 2026.",
    articleSlugs: []
  },
  {
    id: "2026-03-11-evening",
    title: "HackWire Daily Evening Brief — March 11, 2026",
    date: "2026-03-11",
    edition: "evening",
    duration: "5:00",
    audioUrl: "/podcast/episodes/hackwire-daily-2026-03-11-evening.mp3",
    description: "Top cybersecurity stories from March 11, 2026.",
    articleSlugs: []
  }
]
