export type Episode = {
  id: string
  title: string
  date: string
  edition: 'morning' | 'evening'
  duration: string
  audioUrl: string
  description: string
  articleSlugs: string[]
}

// Auto-generated by generate-episode.py — do not edit manually
export const episodes: Episode[] = [
  {
    id: "2026-03-13-morning",
    title: "HackWire Daily Morning Brief — March 13, 2026",
    date: "2026-03-13",
    edition: "morning",
    duration: "11:05",
    audioUrl: "/podcast/episodes/hackwire-daily-2026-03-13-morning.mp3",
    description: "AI-generated Slopoly malware in Interlock ransomware, phishing detection strategies for CISOs, AiLock ransomware hits England Hockey, Loblaw data breach forces mass logout, and more.",
    articleSlugs: [
      "threatsday-bulletin-oauth-trap-edr-killer-signal-phishing-zombie-zip-ai-platform",
      "how-to-scale-phishing-detection-in-your-soc-3-steps-for-cisos",
      "ai-generated-slopoly-malware-used-in-interlock-ransomware-attack",
      "ailock-ransomware-claims-england-hockey-data-breach-investigation-launched",
      "loblaw-data-breach-prompts-mass-customer-account-logout"
    ]
  },
  {
    id: "2026-03-12-evening",
    title: "HackWire Daily Evening Wrap — March 12, 2026",
    date: "2026-03-12",
    edition: "evening",
    duration: "5:05",
    audioUrl: "/podcast/episodes/hackwire-daily-2026-03-12-evening.mp3",
    description: "Top cybersecurity stories from March 12, 2026.",
    articleSlugs: []
  },
  {
    id: "2026-03-11-evening",
    title: "HackWire Daily Evening Wrap — March 11, 2026",
    date: "2026-03-11",
    edition: "evening",
    duration: "5:06",
    audioUrl: "/podcast/episodes/hackwire-daily-2026-03-11-evening.mp3",
    description: "Top cybersecurity stories from March 11, 2026.",
    articleSlugs: []
  }
]
