#!/usr/bin/env python3
"""
HackWire Podcast Data Updater
Scans generated episodes and updates podcast-data.ts with latest episodes.
Run after episode generation to register new episodes with the website.
"""

import json
import re
from datetime import datetime
from pathlib import Path
from subprocess import run

# Paths
BASE = Path(__file__).parent
HACKWIRE = BASE.parent
EPISODES_DIR = BASE / "episodes"
PODCAST_DATA_FILE = HACKWIRE / "src" / "lib" / "podcast-data.ts"

def get_mp3_duration(mp3_path: Path) -> str:
    """Extract duration from MP3 using ffprobe."""
    try:
        result = run(
            ["ffprobe", "-v", "error", "-show_entries", "format=duration", "-of", "default=noprint_wrappers=1:nokey=1:novalue=1", str(mp3_path)],
            capture_output=True, text=True, timeout=10
        )
        if result.stdout.strip():
            seconds = float(result.stdout.strip())
            minutes = int(seconds // 60)
            secs = int(seconds % 60)
            return f"{minutes}:{secs:02d}"
    except Exception as e:
        print(f"  Warning: Could not get duration for {mp3_path.name}: {e}")
    return "5:00"  # Default fallback

def parse_episode_file(mp3_path: Path) -> dict | None:
    """
    Extract episode metadata from filename.
    Format: hackwire-daily-2026-03-14-morning.mp3
    """
    name = mp3_path.stem.replace(".voice", "")  # Remove .voice suffix
    pattern = r"hackwire-daily-(\d{4})-(\d{2})-(\d{2})-(morning|evening)"
    match = re.match(pattern, name)
    
    if not match:
        return None
    
    year, month, day, edition = match.groups()
    date_str = f"{year}-{month}-{day}"
    
    # Only process the final MP3 (not the .voice variant)
    if ".voice" in mp3_path.stem:
        return None
    
    return {
        "date": date_str,
        "edition": edition,
        "file": mp3_path.name,
        "duration": get_mp3_duration(mp3_path)
    }

def scan_episodes() -> list[dict]:
    """Scan episodes directory and return sorted list of episodes."""
    episodes = []
    
    for mp3_file in sorted(EPISODES_DIR.glob("*.mp3")):
        # Skip voice files (use the main MP3)
        if ".voice" in mp3_file.stem:
            continue
        
        ep = parse_episode_file(mp3_file)
        if ep:
            episodes.append(ep)
    
    # Sort by date descending (newest first)
    episodes.sort(key=lambda x: x["date"], reverse=True)
    return episodes

def generate_episode_object(ep: dict) -> str:
    """Generate TypeScript episode object."""
    date = ep["date"]
    edition = ep["edition"]
    duration = ep["duration"]
    
    title = f"HackWire Daily {edition.title()} Brief — {datetime.strptime(date, '%Y-%m-%d').strftime('%B %d, %Y')}"
    description = f"Top cybersecurity stories from {datetime.strptime(date, '%Y-%m-%d').strftime('%B %d, %Y')}."
    
    audio_url = f"/podcast/episodes/{ep['file'].replace('.mp3', '')}.mp3"
    episode_id = f"{date}-{edition}"
    
    return f'''  {{
    id: "{episode_id}",
    title: "{title}",
    date: "{date}",
    edition: "{edition}",
    duration: "{duration}",
    audioUrl: "{audio_url}",
    description: "{description}",
    articleSlugs: []
  }}'''

def update_podcast_data(episodes: list[dict]) -> bool:
    """Update podcast-data.ts with latest episodes."""
    if not episodes:
        print("❌ No episodes found to add")
        return False
    
    # Generate episode objects
    episode_objects = []
    for ep in episodes[:20]:  # Limit to last 20 episodes
        try:
            obj = generate_episode_object(ep)
            episode_objects.append(obj)
        except Exception as e:
            print(f"  Warning: Could not generate object for {ep}: {e}")
    
    # Build new file content
    episodes_array = ",\n".join(episode_objects)
    
    new_content = f"""export type Episode = {{
  id: string
  title: string
  date: string
  edition: 'morning' | 'evening'
  duration: string
  audioUrl: string
  description: string
  articleSlugs: string[]
}}

// Auto-generated by update-podcast-data.py — do not edit manually
export const episodes: Episode[] = [
{episodes_array}
]
"""
    
    try:
        PODCAST_DATA_FILE.write_text(new_content)
        print(f"✅ Updated {PODCAST_DATA_FILE.name} with {len(episodes)} episodes")
        return True
    except Exception as e:
        print(f"❌ Failed to update podcast-data.ts: {e}")
        return False

def main():
    print("🎙️ HackWire Podcast Data Updater")
    print("=" * 60)
    
    if not EPISODES_DIR.exists():
        print(f"❌ Episodes directory not found: {EPISODES_DIR}")
        return False
    
    print(f"📂 Scanning: {EPISODES_DIR}")
    episodes = scan_episodes()
    
    if not episodes:
        print("⚠️ No episodes found")
        return False
    
    print(f"✅ Found {len(episodes)} episodes")
    print(f"\nLatest episodes:")
    for ep in episodes[:5]:
        print(f"  • {ep['date']} ({ep['edition'].upper()}) - {ep['duration']}")
    
    print(f"\n📝 Updating {PODCAST_DATA_FILE.name}...")
    success = update_podcast_data(episodes)
    
    if success:
        print(f"\n✅ Podcast data updated successfully")
        return True
    else:
        print(f"\n❌ Failed to update podcast data")
        return False

if __name__ == "__main__":
    success = main()
    exit(0 if success else 1)
