#!/bin/bash

echo "======================================"
echo "YouTube Service Account Setup"
echo "======================================"
echo ""
echo "Service Account Email:"
echo "hackwire-automation@hackwire-automation.iam.gserviceaccount.com"
echo ""
echo "NEXT STEPS (Andy does these in Google Cloud):"
echo "1. Go to YouTube Studio for HackWire Daily channel"
echo "2. Settings → Permissions"
echo "3. Click 'Add user'"
echo "4. Paste the email above"
echo "5. Select EDITOR role"
echo "6. Click INVITE"
echo "7. Wait 60 seconds for auto-acceptance"
echo ""
echo "Once done, the YouTube upload will work!"
echo "======================================"
